import type { Icon } from '@phosphor-icons/react';
import {
  AirplaneTiltIcon,
  ArrowsLeftRightIcon,
  BabyIcon,
  BankIcon,
  BarbellIcon,
  BasketIcon,
  BeerBottleIcon,
  BicycleIcon,
  BookOpenIcon,
  BriefcaseIcon,
  BusIcon,
  CarIcon,
  ChartLineUpIcon,
  CoffeeIcon,
  CoinsIcon,
  CouchIcon,
  CreditCardIcon,
  DeviceMobileIcon,
  DotsThreeCircleIcon,
  DropIcon,
  FilmSlateIcon,
  ForkKnifeIcon,
  GameControllerIcon,
  GasPumpIcon,
  GiftIcon,
  GraduationCapIcon,
  HamburgerIcon,
  HammerIcon,
  HandHeartIcon,
  HeartbeatIcon,
  HouseIcon,
  LaptopIcon,
  LightningIcon,
  MartiniIcon,
  MusicNotesIcon,
  PawPrintIcon,
  PiggyBankIcon,
  PillIcon,
  PizzaIcon,
  PlantIcon,
  QuestionIcon,
  ReceiptIcon,
  RepeatIcon,
  ScissorsIcon,
  ShieldCheckIcon,
  ShoppingBagIcon,
  ShoppingCartIcon,
  SparkleIcon,
  StorefrontIcon,
  SuitcaseIcon,
  TShirtIcon,
  TagIcon,
  TaxiIcon,
  TelevisionIcon,
  TicketIcon,
  ToothIcon,
  TrainIcon,
  WifiHighIcon,
  WrenchIcon,
} from '@phosphor-icons/react';

/** Icons a category can use, keyed by the value stored in `categories.icon`. */
export const CATEGORY_ICONS: { key: string; label: string; icon: Icon }[] = [
  { key: 'cart', label: 'Groceries', icon: ShoppingCartIcon },
  { key: 'basket', label: 'Basket', icon: BasketIcon },
  { key: 'fork-knife', label: 'Dining', icon: ForkKnifeIcon },
  { key: 'coffee', label: 'Coffee', icon: CoffeeIcon },
  { key: 'burger', label: 'Takeaway', icon: HamburgerIcon },
  { key: 'pizza', label: 'Pizza', icon: PizzaIcon },
  { key: 'beer', label: 'Drinks', icon: BeerBottleIcon },
  { key: 'martini', label: 'Bars', icon: MartiniIcon },
  { key: 'car', label: 'Car', icon: CarIcon },
  { key: 'fuel', label: 'Fuel', icon: GasPumpIcon },
  { key: 'bus', label: 'Bus', icon: BusIcon },
  { key: 'train', label: 'Train', icon: TrainIcon },
  { key: 'taxi', label: 'Taxi', icon: TaxiIcon },
  { key: 'bike', label: 'Bike', icon: BicycleIcon },
  { key: 'house', label: 'Home', icon: HouseIcon },
  { key: 'couch', label: 'Furniture', icon: CouchIcon },
  { key: 'hammer', label: 'DIY', icon: HammerIcon },
  { key: 'wrench', label: 'Repairs', icon: WrenchIcon },
  { key: 'plant', label: 'Garden', icon: PlantIcon },
  { key: 'lightning', label: 'Power', icon: LightningIcon },
  { key: 'water', label: 'Water', icon: DropIcon },
  { key: 'wifi', label: 'Internet', icon: WifiHighIcon },
  { key: 'phone', label: 'Phone', icon: DeviceMobileIcon },
  { key: 'tv', label: 'TV', icon: TelevisionIcon },
  { key: 'laptop', label: 'Tech', icon: LaptopIcon },
  { key: 'film', label: 'Movies', icon: FilmSlateIcon },
  { key: 'game', label: 'Games', icon: GameControllerIcon },
  { key: 'music', label: 'Music', icon: MusicNotesIcon },
  { key: 'ticket', label: 'Events', icon: TicketIcon },
  { key: 'heartbeat', label: 'Health', icon: HeartbeatIcon },
  { key: 'barbell', label: 'Fitness', icon: BarbellIcon },
  { key: 'pill', label: 'Pharmacy', icon: PillIcon },
  { key: 'tooth', label: 'Dental', icon: ToothIcon },
  { key: 'sparkle', label: 'Beauty', icon: SparkleIcon },
  { key: 'scissors', label: 'Hair', icon: ScissorsIcon },
  { key: 'bag', label: 'Shopping', icon: ShoppingBagIcon },
  { key: 'shirt', label: 'Clothes', icon: TShirtIcon },
  { key: 'store', label: 'Shops', icon: StorefrontIcon },
  { key: 'gift', label: 'Gifts', icon: GiftIcon },
  { key: 'paw', label: 'Pets', icon: PawPrintIcon },
  { key: 'baby', label: 'Kids', icon: BabyIcon },
  { key: 'school', label: 'Education', icon: GraduationCapIcon },
  { key: 'book', label: 'Books', icon: BookOpenIcon },
  { key: 'airplane', label: 'Travel', icon: AirplaneTiltIcon },
  { key: 'suitcase', label: 'Holidays', icon: SuitcaseIcon },
  { key: 'repeat', label: 'Subscriptions', icon: RepeatIcon },
  { key: 'shield', label: 'Insurance', icon: ShieldCheckIcon },
  { key: 'bank', label: 'Loans', icon: BankIcon },
  { key: 'chart-up', label: 'Investing', icon: ChartLineUpIcon },
  { key: 'piggy', label: 'Savings', icon: PiggyBankIcon },
  { key: 'card', label: 'Cards', icon: CreditCardIcon },
  { key: 'receipt', label: 'Bills', icon: ReceiptIcon },
  { key: 'arrows', label: 'Transfers', icon: ArrowsLeftRightIcon },
  { key: 'coins', label: 'Income', icon: CoinsIcon },
  { key: 'briefcase', label: 'Work', icon: BriefcaseIcon },
  { key: 'heart', label: 'Donations', icon: HandHeartIcon },
  { key: 'tag', label: 'Tag', icon: TagIcon },
  { key: 'dots', label: 'Other', icon: DotsThreeCircleIcon },
];

const BY_KEY = new Map(CATEGORY_ICONS.map((i) => [i.key, i.icon]));

// Older data (and anything without a chosen icon) falls back to the category name.
const BY_NAME: Record<string, Icon> = {
  groceries: ShoppingCartIcon,
  'dining out': ForkKnifeIcon,
  transport: CarIcon,
  housing: HouseIcon,
  utilities: LightningIcon,
  entertainment: FilmSlateIcon,
  health: HeartbeatIcon,
  shopping: ShoppingBagIcon,
  subscriptions: RepeatIcon,
  travel: AirplaneTiltIcon,
  insurance: ShieldCheckIcon,
  'loan repayment': BankIcon,
  'investments & finances': ChartLineUpIcon,
  'transfers & fees': ArrowsLeftRightIcon,
  income: CoinsIcon,
  other: DotsThreeCircleIcon,
};

/** The glyph for a category: its chosen icon, else one matching its name, else a tag. */
export function iconForCategory(name: string | null | undefined, icon?: string | null): Icon {
  if (!name) return QuestionIcon;
  return (icon && BY_KEY.get(icon)) || BY_NAME[name.trim().toLowerCase()] || TagIcon;
}

/** A tidy palette for category colours. */
export const CATEGORY_COLORS = [
  '#22c55e', '#84cc16', '#eab308', '#f59e0b', '#f97316', '#ef4444', '#f43f5e', '#ec4899',
  '#d946ef', '#a855f7', '#8b5cf6', '#6366f1', '#3b82f6', '#0ea5e9', '#06b6d4', '#14b8a6',
  '#10b981', '#94a3b8', '#64748b', '#a8a29e',
];
